#!/bin/sh

PREFIX="js-"

LOG=/var/log/atmo/dhcp_hostname.log

# Function: get_hostname()
# Description: Gets the hostname, depending on the distro
get_hostname() {
   hostname_value=$(curl -s 'http://169.254.169.254/openstack/latest/meta_data.json' | python -mjson.tool | sed -n -e '/"hostname":/ s/^.*"\(.*\)".*/\1/p')
}

# This function will lookup the ip address
reverse_lookup ()  {
  if [ -n "$1" ]; then
    local ip=$1
    local htemp=$(dig -x $ip +short)
    echo $(date +"%m%d%y %H:%M:%S") "      DEBUG: hostname returned from dig = $htemp" >> $LOG
    if [ $? -eq 0 -a -n "$htemp" ]; then
      hostname_value=$(echo $htemp | sed 's/\.$//')
    fi
  fi
}

MAX_ATTEMPTS=5

retry=0
hostname_value=""

echo $(date +"%m%d%y %H:%M:%S") "dhclient hostname hook started" >> $LOG

while [ $retry -lt $MAX_ATTEMPTS -a -z "$hostname_value" ]; do
    retry=$((retry+1))
    echo $(date +"%m%d%y %H:%M:%S") "   Attempt #${retry}" >> $LOG
    # Note: gobal hostname_value is returned
    get_hostname
    sleep 1
done

# we want the domain to be "jestreamlocal"
hostname_value=`echo "$hostname_value" | sed 's/novalocal/jetstreamlocal/'`

# retest hostname value
if [ -z $hostname_value ]; then
    domainname="jetstreamlocal"
    third_octet=$(echo $myip | cut -f 3 -d '.')
    fourth_octet=$(echo $myip | cut -f 4 -d '.')
    fallback_hostname=${PREFIX}${third_octet}-${fourth_octet}${domainname}
    # Set hostname to constructed hostname, not machine default
    hostname $fallback_hostname
    echo $(date +"%m%d%y %H:%M:%S") " Hostname could not be determined. using `hostname`" >> $LOG
else
    hostname $hostname_value
    echo $hostname_value > /etc/hostname
    hostname_value_short=$(echo $hostname_value | sed "s/\..*//")
    myip=$(dig $hostname_value +short)
    sed -ri "/^.*vm[0-9]+-[0-9]+\.cyverse\.org.*$/d" /etc/hosts
    grep -q "$myip $hostname_value $hostname_value_short" /etc/hosts || echo "$myip $hostname_value $hostname_value_short" >> /etc/hosts
    echo $(date +"%m%d%y %H:%M:%S") "   Hostname has been set to `hostname`" >> $LOG
fi


# make sure we have the correct route to wrangler nas
if ! (route -n | grep 149.165.238.53) >/dev/null 2>&1; then
    logger "Fixing static route to Wrangler NFS"
    route add -net 149.165.238.53 netmask 255.255.255.255 gw 10.5.0.129
fi

